### ISSUE TITLE
Set up Cypress testing framework

### ISSUE THREAD

**Issue by billiemj** [billiemj/client-panel#6]
https://www.cypress.io/

**Comment by billiemj** [comment]
[Guides](https://docs.cypress.io/guides/overview/why-cypress.html#In-a-nutshell)

# To-do
## Getting Started
- [x] Install Cypress
- [ ]  Write first test
- [ ]  Test app

## Core Concepts
- [ ]  Introduction to Cypress
- [ ]  Writing and organizing tests
- [ ]  Retry-ability
- [ ]  Interacting with Elements
- [ ] Variables and aliases
- [ ]  Conditional Testing
- [ ]  The test runner
- [ ]  Dashboard Service
